command_line:    
  - sensor:
      name: shopping_list_unchecked_items
      command: /config/external_scripts/print_unchecked_shopping_list_items.py

script: !include_dir_merge_named scripts/
automation: !include_dir_merge_list automations/
