# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: EDI-Habitat
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 10
  unit_system: metric
  time_zone: !secret timezone
  packages:
    persons: !include packages/persons/persons.yaml
    voice_assistant: !include packages/voice_assistant/voice_assistant.yaml
    lights: !include packages/lights/lights.yaml
    hvac: !include packages/hvac/hvac.yaml
    octoprint: !include packages/octoprint/octoprint.yaml
    shopping_list: !include packages/shopping_list/shopping_list.yaml
    telegram: !include packages/telegram/telegram.yaml
    system_monitoring: !include packages/system_monitoring/system_monitoring.yaml
  customize: !include customize.yaml

lovelace:
  mode: yaml

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Records states to the db
recorder:

# Record some of our data to influxdb so it can be visualized in grafana
influxdb:
  host: !secret influxdb_host
  port: !secret influxdb_port
  username: !secret influxdb_username
  password: !secret influxdb_password
  precision: ms
  include:
    entities:
      - sensor.droopy_power
      - sensor.humidifier_power
      - sensor.droopy_consumption
      - sensor.humidifier_consumption
      - sensor.office_light_sensor
      - sensor.living_room_light_sensor
      - binary_sensor.living_room_motion_sensor
      - binary_sensor.office_motion_sensor

weather:
  - platform: buienradar
    name: "Home"
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    forecast: true

# Sensors
sensor: 
  - platform: buienradar
    timeframe: 120
    monitored_conditions:
      - conditionexact
      - humidity
      - temperature
      - windspeed
      - winddirection
      - precipitation_forecast_total
      - temperature_1d
      - rain_1d
      - rainchance_1d

# Text to speech
tts:
  - platform: google_translate

shopping_list:

#group: !include groups.yaml
#automation: !include automations.yaml
#script: !include scripts.yaml
