# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: EDI-Habitat
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 10
  unit_system: metric
  currency: EUR
  time_zone: !secret timezone
  country: !secret country
  packages:
    persons: !include packages/persons/persons.yaml
    voice_assistant: !include packages/voice_assistant/voice_assistant.yaml
    lights: !include packages/lights/lights.yaml
    hvac: !include packages/hvac/hvac.yaml
    octoprint: !include packages/octoprint/octoprint.yaml
    shopping_list: !include packages/shopping_list/shopping_list.yaml
    telegram: !include packages/telegram/telegram.yaml
    system_monitoring: !include packages/system_monitoring/system_monitoring.yaml
    entertainment: !include packages/entertainment/entertainment.yaml
  customize: !include customize.yaml

lovelace:
  mode: yaml

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Records states to the db
recorder:

# Record some of our data to influxdb so it can be visualized in grafana
influxdb:
  host: !secret influxdb_host
  port: !secret influxdb_port
  username: !secret influxdb_username
  password: !secret influxdb_password
  include:
    entities:
      - sensor.droopy_power
      - sensor.humidifier_power
      - sensor.droopy_consumption
      - sensor.humidifier_consumption
      - sensor.office_light_sensor
      - sensor.living_room_light_sensor
      - binary_sensor.living_room_motion_sensor
      - binary_sensor.office_motion_sensor
      - sensor.living_room_temperature
      - sensor.living_room_humidity
      - sensor.bedroom_temperature
      - sensor.bedroom_humidity
      - sensor.bathroom_temperature
      - sensor.bathroom_humidity
      - sensor.office_temperature
      - sensor.office_humidity
      - sensor.filament_box_temperature
      - sensor.filament_box_humidity
      - sensor.balcony_temperature
      - sensor.balcony_humidity
      - light.living_room_ceiling_light_1
      - light.living_room_ceiling_light_2
      - light.fado_lamp
      - light.corner_lamp
      - light.kitchen_ceiling_light
      - light.balcony_ceiling_light
      - light.hall_ceiling_light
      - light.boiler_room_ceiling_light
      - light.closet_ceiling_light
      - light.toilet_ceiling_light
      - light.bathroom_ceiling_light
      - light.office_ceiling_light
      - light.office_lamp
      - light.office_droopy_lamp
      - light.office_work_desk_lamp
      - light.bedroom_ceiling_light
      - light.bedroom_lamp
      - switch.kitchen_stove_light
      - switch.balcony_string_lights
      - switch.bedroom_nightstand_light

# Text to speech
tts:
  - platform: google_translate

shopping_list:

#group: !include groups.yaml
#automation: !include automations.yaml
#script: !include scripts.yaml
