# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: EDI-Habitat
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 10
  unit_system: metric
  currency: EUR
  time_zone: !secret timezone
  country: !secret country
  packages:
    persons: !include packages/persons/persons.yaml
    voice_assistant: !include packages/voice_assistant/voice_assistant.yaml
    lights: !include packages/lights/lights.yaml
    hvac: !include packages/hvac/hvac.yaml
    octoprint: !include packages/octoprint/octoprint.yaml
    shopping_list: !include packages/shopping_list/shopping_list.yaml
    telegram: !include packages/telegram/telegram.yaml
    system_monitoring: !include packages/system_monitoring/system_monitoring.yaml
    entertainment: !include packages/entertainment/entertainment.yaml
  customize: !include customize.yaml

lovelace:
  resource_mode: yaml
  dashboards:
    lovelace:
      mode: yaml
      filename: ui-lovelace.yaml
      title: Home
      icon: mdi:view-dashboard
      show_in_sidebar: true

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Records states to the db
recorder:

# Text to speech
tts:
  - platform: google_translate

input_select:
  floor_plan:
    name: Floor Selector
    options:
      - garden
      - ground
      - first
      - attic
    initial: ground
    icon: mdi:floor-plan

scene: !include scenes.yaml

# group: !include groups.yaml
# automation: !include automations.yaml
# script: !include scripts.yaml
