title: EDI-Habitat
views:
  - path: default_view
    title: "Home"
    icon: mdi:home
    badges:
      - entity: person.joao
      - entity: person.jelena
    cards:
      - type: weather-forecast
        entity: weather.home
        show_forecast: true
      - type: shopping-list
        title: Shopping List
      - type: vertical-stack
        cards:
          - type: grid
            title: "Living Room"
            columns: 2
            cards:
              - type: sensor
                entity: sensor.living_room_temperature
                name: "Temperature"
                graph: line
              - type: sensor
                entity: sensor.living_room_humidity
                name: "Humidity"
                graph: line
          - type: grid
            title: "Bedroom"
            columns: 2
            cards:
              - type: sensor
                entity: sensor.bedroom_temperature
                name: "Temperature"
                graph: line
              - type: sensor
                entity: sensor.bedroom_humidity
                name: "Humidity"
                graph: line
          - type: grid
            title: "Office"
            columns: 2
            cards:
              - type: sensor
                entity: sensor.office_temperature
                name: "Temperature"
                graph: line
              - type: sensor
                entity: sensor.office_humidity
                name: "Humidity"
                graph: line
          - type: grid
            title: "Filament Box"
            columns: 2
            cards:
              - type: sensor
                entity: sensor.filament_box_temperature
                name: "Temperature"
                graph: line
              - type: sensor
                entity: sensor.filament_box_humidity
                name: "Humidity"
                graph: line
          - type: grid
            title: "Balcony"
            columns: 2
            cards:
              - type: sensor
                entity: sensor.balcony_temperature
                name: "Temperature"
                graph: line
              - type: sensor
                entity: sensor.balcony_humidity
                name: "Humidity"
                graph: line
      - type: history-graph
        title: "Lux Graph"
        entities:
          - sensor.office_light_sensor
          - sensor.living_room_light_sensor
        hours_to_show: 24
        refresh_interval: 10
  - path: lights
    title: House Lights
    icon: mdi:lightbulb-on-outline
    cards:
      - type: grid
        title: "Living Room"
        cards:
          - type: light
            entity: light.living_room_ceiling_light_1
            name: "Ceiling Light 1"
          - type: light
            entity: light.living_room_ceiling_light_2
            name: "Ceiling Light 2"
          - type: light
            entity: light.fado_light
            name: "Fado Light"
          - type: light
            entity: light.tv_lamp
            name: "TV Lamp"
          - type: light
            entity: light.corner_lamp
            name: "Corner Lamp"
      - type: grid
        title: "Kitchen"
        cards:
          - type: light
            entity: light.kitchen_ceiling_light
            name: "Ceiling Light"
          - type: button
            name: "Stove Light"
            entity: switch.kitchen_stove_light
            icon: mdi:lightbulb
      - type: grid
        title: "Balcony"
        cards:
          - type: light
            entity: light.balcony_ceiling_light
            name: "Ceiling Light"
      - type: grid
        title: "Hallway"
        cards:
          - type: light
            entity: light.hall_ceiling_light
            name: "Ceiling Light"
      - type: grid
        title: "Bedroom"
        cards:
          - type: light
            entity: light.bedroom_ceiling_light
            name: "Ceiling Light"
          - type: light
            entity: light.bedroom_lamp
            name: "Lamp"
      - type: grid
        title: "Office"
        cards:
          - type: light
            entity: light.office_ceiling_light
            name: "Ceiling Light"
          - type: light
            entity: light.office_lamp
            name: "Lamp"
          - type: light
            entity: light.office_droopy_lamp
            name: "Droopy Lamp"
          - type: light
            entity: light.office_work_desk_lamp
            name: "Work Desk Lamp"
  - path: printer
    title: 3D Printer
    icon: mdi:printer-3d
    cards:
      - type: vertical-stack
        title: Droopy Power
        cards:
          - type: entity
            name: Status
            entity: sensor.droopy_power_status
          - type: grid
            columns: 2
            cards:
              - type: button
                name: "On/Off"
                icon: mdi:power-cycle
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.power_cycle_droopy
              - type: button
                name: "Emergency Off"
                icon: mdi:flash-alert-outline
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.emergency_power_off_droopy
      - type: entities
        title: "Droopy Status"
        entities:
           - sensor.droopy_current_state
           - sensor.droopy_actual_tool0_temp
           - sensor.droopy_actual_bed_temp
           - sensor.droopy_target_tool0_temp
           - sensor.droopy_target_bed_temp
           - sensor.droopy_job_percentage
           - sensor.droopy_time_remaining
           - sensor.droopy_time_elapsed
  - path: monitoring
    title: "Monitoring"
    icon: mdi:monitor-eye
    badges:
      - entity: binary_sensor.updater
    cards:
      - type: entities
        title: "CPU Temperature of House Pis"
        entities:
          - sensor.edi_cpu_temperature
          - sensor.pi_hole_cpu_temperature
          - sensor.octopi_cpu_temperature
      - type: entities
        title: "Sensor Batteries"
        entities:
          - sensor.kitchen_switch_battery_level
          - sensor.living_room_switch_battery_level
          - sensor.balcony_switch_battery_level
          - sensor.cuby_battery_level
          - sensor.hall_switch_battery_level
          - sensor.office_droopy_lamp_switch_battery_level
          - sensor.office_work_desk_lamp_switch_battery_level
          - sensor.office_switch_battery_level
          - sensor.bedroom_switch_battery_level
          - sensor.office_motion_light_sensor_battery_level
          - sensor.living_room_motion_light_sensor_battery_level
          - sensor.living_room_temperature_battery_level
          - sensor.balcony_temperature_battery_level
          - sensor.bedroom_temperature_battery_level
          - sensor.office_temperature_battery_level
          - sensor.filament_box_temperature_battery_level
