title: EDI-Habitat
views:
  - path: default_view
    title: "Home"
    icon: mdi:home
    badges:
      - entity: person.joao
      - entity: person.jelena
    cards:
      - type: weather-forecast
        entity: weather.home
        show_forecast: true
      - type: vertical-stack
        cards:
          - type: grid
            title: "Living Room"
            columns: 2
            cards:
              - type: sensor
                entity: sensor.living_room_temperature
                name: "Temperature"
                graph: line
              - type: sensor
                entity: sensor.living_room_humidity
                name: "Humidity"
                graph: line
          - type: grid
            title: "Bedroom"
            columns: 2
            cards:
              - type: sensor
                entity: sensor.bedroom_temperature
                name: "Temperature"
                graph: line
              - type: sensor
                entity: sensor.bedroom_humidity
                name: "Humidity"
                graph: line
          - type: grid
            title: "Office"
            columns: 2
            cards:
              - type: sensor
                entity: sensor.office_temperature
                name: "Temperature"
                graph: line
              - type: sensor
                entity: sensor.office_humidity
                name: "Humidity"
                graph: line
          - type: grid
            title: "PLA Container"
            columns: 2
            cards:
              - type: sensor
                entity: sensor.pla_container_temperature
                name: "Temperature"
                graph: line
              - type: sensor
                entity: sensor.pla_container_humidity
                name: "Humidity"
                graph: line    
      - type: history-graph
        title: "Lux Graph"
        entities:
          - sensor.office_light_sensor
          - sensor.living_room_light_sensor
        hours_to_show: 24
        refresh_interval: 10
  - path: lights
    title: House Lights
    icon: mdi:lightbulb-on-outline
    cards:
      - type: grid
        title: "Living Room"
        cards:
          - type: light
            entity: light.living_room_main_light_1
            name: "Ceiling Light 1"
          - type: light
            entity: light.living_room_main_light_2
            name: "Ceiling Light 2"
          - type: light
            entity: light.fado_light
            name: "Fado Light"
          - type: light
            entity: light.tv_lamp
            name: "TV Lamp"
          - type: light
            entity: light.corner_lamp
            name: "Corner Lamp"
      - type: grid
        title: "Kitchen"
        cards:
          - type: light
            entity: light.kitchen_main_light
            name: "Ceiling Light"
          - type: button
            name: "Stove Light"
            entity: switch.kitchen_stove_light
            icon: mdi:lightbulb
      - type: grid
        title: "Hallway"
        cards:
          - type: light
            entity: light.hall_main_light
            name: "Ceiling Light"
      - type: grid
        title: "Bedroom"
        cards:
          - type: light
            entity: light.bedroom_main_light
            name: "Ceiling Light"
          - type: light
            entity: light.bedroom_lamp
            name: "Lamp"
      - type: grid
        title: "Office"
        cards:
          - type: light
            entity: light.office_main_light
            name: "Ceiling Light"
          - type: light
            entity: light.office_lamp
            name: "Lamp"
  - path: printer
    title: 3D Printer
    icon: mdi:printer-3d
    cards:
      - type: vertical-stack
        title: Droopy Power
        cards:
          - type: entity
            name: Status
            entity: sensor.droopy_power_status
          - type: grid
            columns: 2
            cards:
              - type: button
                name: "On/Off"
                icon: mdi:power-cycle
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.power_cycle_droopy
              - type: button
                name: "Emergency Off"
                icon: mdi:flash-alert-outline
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.emergency_power_off_droopy
      - type: entities
        title: "Droopy Status"
        entities:
           - sensor.droopy_current_state
           - sensor.droopy_actual_tool0_temp
           - sensor.droopy_actual_bed_temp
           - sensor.droopy_target_tool0_temp
           - sensor.droopy_target_bed_temp
           - sensor.droopy_job_percentage
           - sensor.droopy_time_remaining
           - sensor.droopy_time_elapsed
  - path: settings
    title: "Settings"
    icon: mdi:application-cog
    badges:
      - entity: binary_sensor.updater
    cards:
      - type: entities
        entities:
          - entity: group.cpu_temp
      - type: entities
        entities:
          - entity: group.battery_levels
