device_tracker:
  - platform: mqtt
    devices:
      tile_joao: "bouncer/presence/tile_joao"
      tile_jelena: "bouncer/presence/tile_jelena"
      tile_guest1: "bouncer/presence/tile_guest1"
      tile_guest2: "bouncer/presence/tile_guest2"
    qos: 0
    payload_home: "home"
    payload_not_home: "not_home"

person:
  - name: João
    id: !secret joao_id
    device_trackers:
      - device_tracker.tile_joao
  - name: Jelena
    id: !secret jelena_id
    device_trackers:
      - device_tracker.tile_jelena
  - name: Guest1
    id: guest1id1234
    device_trackers:
      - device_tracker.tile_guest1
  - name: Guest2
    id: guest2id1234
    device_trackers:
      - device_tracker.tile_guest2

automation: !include_dir_merge_list automations/
