person:
  - name: João
    id: !secret joao_id
    device_trackers:
      - device_tracker.tile_joao
  - name: Jelena
    id: !secret jelena_id
    device_trackers:
      - device_tracker.tile_jelena

sensor:        
  - platform: mqtt
    state_topic: 'monitor/presence/tile_joao'
    value_template: '{{ value_json.confidence }}'
    unit_of_measurement: '%'
    name: 'Joao Occupancy Confidence'

  - platform: mqtt
    state_topic: 'monitor/presence/tile_jelena'
    value_template: '{{ value_json.confidence }}'
    unit_of_measurement: '%'
    name: 'Jelena Occupancy Confidence'

automation: !include_dir_merge_list automations/
