mqtt:
  device_tracker:
  - name: "tile_joao"
    state_topic: "bouncer/presence/tile_joao"
    qos: 0
    payload_home: "home"
    payload_not_home: "not_home"
  - name: "tile_jelena"
    state_topic: "bouncer/presence/tile_jelena"
    qos: 0
    payload_home: "home"
    payload_not_home: "not_home"
  - name: "tile_guest1"
    state_topic: "bouncer/presence/tile_guest1"
    qos: 0
    payload_home: "home"
    payload_not_home: "not_home"
  - name: "tile_guest2"
    state_topic: "bouncer/presence/tile_guest2"
    qos: 0
    payload_home: "home"
    payload_not_home: "not_home"

person:
  - name: João
    id: !secret joao_id
    device_trackers:
      - device_tracker.tile_joao
  - name: Jelena
    id: !secret jelena_id
    device_trackers:
      - device_tracker.tile_jelena
  - name: Guest1
    id: guest1id1234
    device_trackers:
      - device_tracker.tile_guest1
  - name: Guest2
    id: guest2id1234
    device_trackers:
      - device_tracker.tile_guest2

input_boolean:
  enable_joao:
    name: Enable joao for automations
  enable_jelena:
    name: Enable jelena for automations
  enable_guest1:
    name: Enable guest1 for automations
  enable_guest2:
    name: Enable guest2 for automations

template:
  - binary_sensor:
      - name: Someone Home
        state: > 
          {% set someone_home = false %}
          {% if is_state('input_boolean.enable_joao', 'on') %}
            {% set someone_home = someone_home or is_state('person.joao', 'home') %}
          {% endif %}
          {% if is_state('input_boolean.enable_jelena', 'on') %}
            {% set someone_home = someone_home or is_state('person.jelena', 'home') %}
          {% endif %}
          {% if is_state('input_boolean.enable_guest1', 'on') %}
            {% set someone_home = someone_home or is_state('person.guest1', 'home') %}
          {% endif %}
          {% if is_state('input_boolean.enable_guest2', 'on') %}
            {% set someone_home = someone_home or is_state('person.guest2', 'home') %}
          {% endif %}

          {% if someone_home %}
            on
          {% else %}
            off
          {% endif %}

automation: !include_dir_merge_list automations/
