- id: auto_shutdown_droopy
  alias: Automatically shutdown droopy when inactive for a while
  triggers:
    - trigger: state
      entity_id: binary_sensor.octoprint_printing
      to: "off"
      for: "00:15:00"
  conditions:
    - condition: state
      entity_id: sensor.octoprint_current_state
      state: "operational"
  actions:
    - action: script.turn_on
      entity_id: script.safely_power_off_droopy
