- id: auto_shutdown_droopy
  alias: Automatically shutdown droopy when inactive for a while
  trigger:
    - platform: state
      entity_id: sensor.droopy_current_state
      to: "Operational"
      for: "00:15:00"
  action:
    - service: script.turn_on
      entity_id: script.safely_power_off_droopy

- id: warn_droopy_idle_10_min
  alias: Warn when droopy is idle for 10 minutes
  trigger:
    - platform: state
      entity_id: sensor.droopy_current_state
      to: "Operational"
      for: "00:10:00"
  action:
    - service: notify.joao
      data:
        message: Droopy has been idle for 10 minutes and will shutdown in 5 minutes.

- id: warn_droopy_idle_14_min
  alias: Warn when droopy is idle for 14 minutes
  trigger:
    - platform: state
      entity_id: sensor.droopy_current_state
      to: "Operational"
      for: "00:14:00"
  action:
    - service: notify.joao
      data:
        message: Droopy has been idle for 14 minutes and will shutdown in 1 minute.