- id: auto_shutdown_droopy
  alias: Automatically shutdown droopy when inactive for a while
  trigger:
    - platform: state
      entity_id: sensor.droopy_current_state
      to: "Operational"
      for: "00:15:00"
  action:
    - service: script.turn_on
      entity_id: script.safely_power_off_droopy