light:
  - platform: switch
    name: Front Door Light
    entity_id: switch.front_door_light
  - platform: switch
    name: Entryway Ceiling Light
    entity_id: switch.entryway_ceiling_light
  - platform: switch
    name: Toilet Ceiling Light
    entity_id: switch.toilet_ceiling_light
  - platform: switch
    name: Kitchen Table Lights
    entity_id: switch.kitchen_table_lights
  - platform: switch
    name: Kitchen Bench Lights
    entity_id: switch.kitchen_bench_lights
  - platform: switch
    name: Living Room Ceiling Lights
    entity_id: switch.living_room_ceiling_lights
  - platform: switch
    name: Living Room TV Stand Light
    entity_id: switch.living_room_tv_stand_light
  - platform: switch
    name: Hallway Ceiling Light
    entity_id: switch.hallway_ceiling_light
  - platform: switch
    name: Office Jelena Ceiling Light
    entity_id: switch.office_jelena_ceiling_light
  - platform: switch
    name: Bedroom Ceiling Light
    entity_id: switch.bedroom_ceiling_light
  - platform: switch
    name: Closet Room Ceiling Light
    entity_id: switch.closet_room_ceiling_light
  - platform: switch
    name: Bathroom Ceiling Light
    entity_id: switch.bathroom_ceiling_light
  - platform: switch
    name: Bathroom Mirror Light
    entity_id: switch.bathroom_mirror_light
  - platform: switch
    name: Attic Ceiling Lights
    entity_id: switch.attic_ceiling_lights
  - platform: switch
    name: Attic Donut Lamp
    entity_id: switch.attic_donut_lamp
  - platform: switch
    name: Shed Outside Light
    entity_id: switch.shed_outside_light
  - platform: switch
    name: Shed Inside Light
    entity_id: switch.shed_inside_light

  - platform: group
    unique_id: living_room_corner_lamp
    name: Living Room Corner Lamp
    entities:
      - light.living_room_corner_lamp_1
      - light.living_room_corner_lamp_2
      - light.living_room_corner_lamp_3
  - platform: group
    unique_id: mechanical_room_ceiling_lights
    name: Mechanical Room Ceiling Lights
    entities:
      - light.mechanical_room_light_1
      - light.mechanical_room_light_2
      - light.mechanical_room_light_3

input_boolean:
  ha_toggle_in_progress:
    name: HA toggle in progress
    initial: off
    icon: mdi:toggle-switch
  halloween_mode:
    name: Halloween Mode
    initial: off
    icon: mdi:halloween

group: !include_dir_merge_named groups/
automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
