shell_command:
  shutdown_octoprint: !secret octoprint_shutdown_ssh

# This input boolean should not be added to the UI and it's set to true via a
# script when droopy is shutting down
input_boolean:
  droopy_shutting_down:
    name: Droopy Shutting Down
    initial: false

template:
  - sensor:
    # This sensor displays the 3 status of droopy. On, Off and Shutting down.
    - name: "Droopy Power Status"
      icon: >
        {% if is_state('input_boolean.droopy_shutting_down', 'on') %}
          mdi:power-plug-outline
        {% elif is_state('switch.droopy', 'on') %}
          mdi:power-plug
        {% else %}
          mdi:power-plug-off-outline
        {% endif %}
      state: >
        {% if is_state('input_boolean.droopy_shutting_down', 'on') %}
          Shutting down...
        {% elif is_state('switch.droopy', 'on') %}
          On
        {% else %}
          Off
        {% endif %}

    - name: "Droopy Estimated Total Time"
      icon: mdi:clock-end
      state: >
        {% if is_state('sensor.octoprint_start_time', 'unavailable') %}
          unavailable
        {% elif is_state('sensor.octoprint_start_time', 'unknown') %}
          unknown
        {% else %}
          {% set start = as_datetime(states.sensor.octoprint_start_time.state) %}
          {% set finish = as_datetime(states.sensor.octoprint_estimated_finish_time.state) %}
          {{ finish - start }}
        {% endif %}

    - name: "Droopy Estimated Finish Time Local"
      icon: mdi:clock-end
      state: >
        {% if is_state('sensor.octoprint_estimated_finish_time', 'unavailable') %}
          unavailable
        {% elif is_state('sensor.octoprint_estimated_finish_time', 'unknown') %}
          unknown
        {% else %}
          {% set finish = as_datetime(states.sensor.octoprint_estimated_finish_time.state) %}
          {{ as_local(finish) }}
        {% endif %}
        
    - name: "Droopy Estimated Remaining Time"
      icon: mdi:clock-end
      state: >
        {% if is_state('sensor.octoprint_estimated_finish_time', 'unavailable') %}
          unavailable
        {% elif is_state('sensor.octoprint_estimated_finish_time', 'unknown') %}
          unknown
        {% else %}
          {% set finish = as_datetime(states.sensor.octoprint_estimated_finish_time.state) %}
          {{ finish - now() }}
        {% endif %}

command_line:
  - sensor:
      name: OctoPi CPU Temperature
      command: !secret octoprint_cpu_temp
      unit_of_measurement: "ºC"
      value_template: >
        {% if is_number(value) %}
          {{ value | multiply(0.001) | round(1) }}
        {% else %}
          {{ value }}
        {% endif %}

automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/