octoprint:
  host: !secret octoprint_host
  api_key: !secret octoprint_api_key
  name: Droopy
  number_of_tools: 1
  bed: true
  sensors:
    monitored_conditions:
      - 'Current State'
      - 'Temperatures'      
      - 'Job Percentage'
      - 'Time Elapsed'
      - 'Time Remaining'
  binary_sensors:
    monitored_conditions:
      - 'Printing'
      - 'Printing Error'

shell_command:
  shutdown_octoprint: !secret octoprint_shutdown_ssh

input_boolean:
  droopy_shutting_down:
    name: Droopy Shutting Down
    initial: false

sensor:
  - platform: template
    sensors:
      droopy_power_status:
        friendly_name: "Droopy Power"
        icon_template: >-
          {% if is_state('input_boolean.droopy_shutting_down', 'on') %}
            mdi:power-plug-outline
          {% elif is_state('switch.droopy', 'on') %}
            mdi:power-plug
          {% else %}
            mdi:power-plug-off-outline
          {% endif %}
        value_template: >-
          {% if is_state('input_boolean.droopy_shutting_down', 'on') %}
            Shutting down...
          {% elif is_state('switch.droopy', 'on') %}
            On
          {% else %}
            Off
          {% endif %}

automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/