shell_command:
  shutdown_dreadnought: !secret dreadnought_shutdown_ssh

wake_on_lan:

switch:
  - platform: wake_on_lan
    name: Dreadnought Toggle
    mac: !secret dreadnought_mac_address
    host: !secret dreadnought_host
    turn_off:
      service: shell_command.shutdown_dreadnought

sensor:
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: processor_temperature
      - type: memory_use_percent
      - type: last_boot

automation: !include_dir_merge_list automations/